server:
  port: 8001

user:
  intercept: false

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: online-course-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456

  redis:
    host: 101.200.49.246

  minio:
    url: http://101.200.49.246:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: work



---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/Course?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: Course
    password: 8JLypSkXfrhtj87e

  redis:
    host: 127.0.0.1

  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: work